export const ActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  GET_PROFILE_INFO_REQUEST: "GET_PROFILE_INFO_REQUEST",
  GET_PROFILE_INFO_SUCCESS: "GET_PROFILE_INFO_SUCCESS",

  EDIT_BUSINESS_REQUEST: "EDIT_BUSINESS_REQUEST",
  EDIT_BUSINESS_SUCCESS: "EDIT_BUSINESS_SUCCESS",

  ADD_BUSINESS_REQUEST: "ADD_BUSINESS_REQUEST",
  ADD_BUSINESS_SUCCESS: "ADD_BUSINESS_SUCCESS",

  GET_BUSINESSES_REQUEST: "GET_BUSINESSES_REQUEST",
  GET_BUSINESSES_SUCCESS: "GET_BUSINESSES_SUCCESS",

  GET_BUSINESS_REQUEST: "GET_BUSINESS_REQUEST",
  GET_BUSINESS_SUCCESS: "GET_BUSINESS_SUCCESS",

  SET_BUSINESS_DETAIL_LOAD_STATUS: "SET_BUSINESS_DETAIL_LOAD_STATUS",
  SET_BUSINESSES_LOAD_STATUS: "SET_BUSINESSES_LOAD_STATUS",

  ADD_SERVICE_REQUEST: "ADD_SERVICE_REQUEST",
  ADD_SERVICE_SUCCESS: "ADD_SERVICE_SUCCESS",

  EDIT_SERVICE_REQUEST: "EDIT_SERVICE_REQUEST",
  EDIT_SERVICE_SUCCESS: "EDIT_SERVICE_SUCCESS",

  GET_SERVICE_REQUEST: "GET_SERVICE_REQUEST",
  GET_SERVICE_SUCCESS: "GET_SERVICE_SUCCESS",

  SET_SERVICE_LOAD_STATUS: "SET_SERVICE_LOAD_STATUS",

  GET_RESERVES_REQUEST: "GET_RESERVES_REQUEST",
  GET_RESERVES_SUCCESS: "GET_RESERVES_SUCCESS",

  ADD_RESERVE_REQUEST: "ADD_RESERVE_REQUEST",
  ADD_RESERVE_SUCCESS: "ADD_RESERVE_SUCCESS",

  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",

  SET_UPLOAD_FILE_STATUS: "SET_UPLOAD_FILE_STATUS",

  ADD_TICKET_REQUEST: "ADD_TICKET_REQUEST",
  ADD_TICKET_SUCCESS: "ADD_TICKET_SUCCESS",
  SELECT_TICKET: "SELECT_TICKET",

  ADD_MESSAGE_TO_TICKET_REQUEST: "ADD_MESSAGE_TO_TICKET_REQUEST",
  ADD_MESSAGE_TO_TICKET_SUCCESS: "ADD_MESSAGE_TO_TICKET_SUCCESS",

  GET_BUSINESS_TICKETS_REQUEST: "GET_BUSINESS_TICKETS_REQUEST",
  GET_BUSINESS_TICKETS_SUCCESS: "GET_BUSINESS_TICKETS_SUCCESS",

  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",

  GET_COMMENTS_REQUEST: "GET_COMMENTS_REQUEST",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",

  GET_BUSINESS_DASHBOARD_REQUEST: "GET_BUSINESS_DASHBOARD_REQUEST",
  GET_BUSINESS_DASHBOARD_SUCCESS: "GET_BUSINESS_DASHBOARD_SUCCESS",

  GET_USER_WALLET_REQUEST: "GET_USER_WALLET_REQUEST",
  GET_USER_WALLET_SUCCESS: "GET_USER_WALLET_SUCCESS",

  CREATE_WALLET_REQUEST: "CREATE_WALLET_REQUEST",
  CREATE_WALLET_SUCCESS: "CREATE_WALLET_SUCCESS",

  EDIT_WALLET_REQUEST: "EDIT_WALLET_REQUEST",
  EDIT_WALLET_SUCCESS: "EDIT_WALLET_SUCCESS",

  WALLET_CHECKOUT_REQUEST: "WALLET_CHECKOUT_REQUEST",
  WALLET_CHECKOUT_SUCCESS: "WALLET_CHECKOUT_SUCCESS",

  GET_TRANSACTIONS_REQUEST: "GET_TRANSACTIONS_REQUEST",
  GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
};
